# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminaltask" do
  name "terminaltask"
  desc "TUI task manager built with Bubble Tea"
  homepage "https://github.com/jacobdanielrose/terminaltask"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminaltask"

  on_macos do
    on_intel do
      url "https://github.com/jacobdanielrose/terminaltask/releases/download/v#{version}/terminaltask_#{version}_darwin_amd64.tar.gz"
      sha256 "15d069d5cae6cbf448f7de60e7e56f4ac3b866a6e0e84f2d0b3a077c261a1229"
    end
    on_arm do
      url "https://github.com/jacobdanielrose/terminaltask/releases/download/v#{version}/terminaltask_#{version}_darwin_arm64.tar.gz"
      sha256 "2ac21ee4dadc47f3b2b501cbb9ec72c6cc487b9b8068acc291c3e03361dafe3f"
    end
  end

  # No zap stanza required
end
