# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminaltask" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "238cf014dae8c813411ce4b26c5cdbceda2c83600ba62aae77fa693f0c668d11"
      url "https://github.com/jacobdanielrose/terminaltask/releases/download/v#{version}/terminaltask_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "654ebe729964dfe6dfaa03ba601227d3d416be1455fcb2b4fdcb30878bf17ad5"
      url "https://github.com/jacobdanielrose/terminaltask/releases/download/v#{version}/terminaltask_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "terminaltask"
  desc "TUI task manager built with Bubble Tea"
  homepage "https://github.com/jacobdanielrose/terminaltask"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminaltask"

  # No zap stanza required

end
